// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import "forge-std/Script.sol";
import { IMarketRegistry } from "../contracts/interfaces/IMarketRegistry.sol";

/// @title OnboardMarkets — Foundry script to create LEVER markets from JSON config
/// @notice Reads market_config.json (generated by onboard_markets.py) and calls
///         MarketRegistry.createMarket() for each entry.
/// @dev Usage:
///   1. Generate config: python scripts/oracle/onboard_markets.py
///   2. Deploy: forge script script/OnboardMarkets.s.sol --rpc-url $RPC --broadcast
contract OnboardMarkets is Script {
    function run() external {
        // Read config from JSON file
        string memory json = vm.readFile("scripts/oracle/market_config.json");

        // Parse array length
        bytes[] memory marketIds = vm.parseJsonBytesArray(json, "$[*].marketId");
        uint256 count = marketIds.length;
        console.log("Markets to onboard:", count);

        // Get MarketRegistry address from env
        address registry = vm.envAddress("MARKET_REGISTRY");
        IMarketRegistry marketRegistry = IMarketRegistry(registry);

        vm.startBroadcast();

        for (uint256 i = 0; i < count; i++) {
            string memory idx = string(abi.encodePacked("[", vm.toString(i), "]"));

            bytes32 marketId = vm.parseJsonBytes32(json, string(abi.encodePacked("$", idx, ".marketId")));
            string memory name = vm.parseJsonString(json, string(abi.encodePacked("$", idx, ".name")));
            string memory externalId = vm.parseJsonString(json, string(abi.encodePacked("$", idx, ".externalMarketId")));
            uint256 resolutionTime = vm.parseJsonUint(json, string(abi.encodePacked("$", idx, ".resolutionTime")));
            uint256 categoryRaw = vm.parseJsonUint(json, string(abi.encodePacked("$", idx, ".category")));
            uint256 allocationWeight = vm.parseJsonUint(json, string(abi.encodePacked("$", idx, ".allocationWeight")));

            IMarketRegistry.MarketCategory category = IMarketRegistry.MarketCategory(categoryRaw);

            console.log("Creating market:", name);

            marketRegistry.createMarket(
                marketId,
                name,
                externalId,
                resolutionTime,
                category,
                allocationWeight
            );
        }

        vm.stopBroadcast();
        console.log("Done. Markets created:", count);
    }
}
