#!/usr/bin/env bash
# LEVER Protocol — ABI Sync Script
# Reads compiled Foundry artifacts from out/ and generates frontend abis.ts
# Run after any contract change: ./scripts/sync-abis.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/out"
DEST="$ROOT/frontend/user-app/src/config/abis.ts"

if [ ! -d "$OUT" ]; then
  echo "ERROR: $OUT not found. Run 'forge build' first."
  exit 1
fi

extract_abi() {
  local contract_name="$1"
  local artifact="$OUT/${contract_name}.sol/${contract_name}.json"
  if [ ! -f "$artifact" ]; then
    echo "WARN: $artifact not found, skipping" >&2
    return
  fi
  python3 -c "
import json, sys
abi = json.load(open('$artifact'))['abi']
# Keep functions and events only (skip errors, constructors, receive, fallback)
filtered = [x for x in abi if x.get('type') in ('function', 'event')]
print(json.dumps(filtered, indent=2))
"
}

echo "Syncing ABIs from $OUT → $DEST"

# Build the TypeScript file
cat > "$DEST" << 'HEADER'
// Auto-generated by scripts/sync-abis.sh from Foundry compiled artifacts.
// Do NOT edit manually — run: ./scripts/sync-abis.sh

HEADER

# Contract name → TS export name
declare -A CONTRACTS=(
  ["MarketRegistry"]="MARKET_REGISTRY_ABI"
  ["OracleAdapter"]="ORACLE_ADAPTER_ABI"
  ["ExecutionEngine"]="EXECUTION_ENGINE_ABI"
  ["PositionManager"]="POSITION_MANAGER_ABI"
  ["AccountManager"]="ACCOUNT_MANAGER_ABI"
  ["LeverVault"]="LEVER_VAULT_ABI"
  ["MockUSDT"]="USDT_ABI"
  ["MarginEngine"]="MARGIN_ENGINE_ABI"
  ["BorrowFeeEngine"]="BORROW_FEE_ENGINE_ABI"
  ["FundingRateEngine"]="FUNDING_RATE_ENGINE_ABI"
  ["LiquidationEngine"]="LIQUIDATION_ENGINE_ABI"
  ["LeverageModel"]="LEVERAGE_MODEL_ABI"
  ["OILimits"]="OI_LIMITS_ABI"
  ["FeeRouter"]="FEE_ROUTER_ABI"
  ["InsuranceFund"]="INSURANCE_FUND_ABI"
  ["RewardsDistributor"]="REWARDS_DISTRIBUTOR_ABI"
  ["SettlementEngine"]="SETTLEMENT_ENGINE_ABI"
)

COUNT=0
for contract in "${!CONTRACTS[@]}"; do
  ts_name="${CONTRACTS[$contract]}"
  abi_json=$(extract_abi "$contract" 2>/dev/null || echo "")
  if [ -z "$abi_json" ]; then
    echo "  SKIP  $contract (not found)"
    continue
  fi
  echo "export const $ts_name = $abi_json as const;" >> "$DEST"
  echo "" >> "$DEST"
  COUNT=$((COUNT + 1))
  echo "  OK    $contract → $ts_name"
done

echo ""
echo "Synced $COUNT contract ABIs to $DEST"
